######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 15 15:50:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += manager.h
SOURCES += main.cpp manager.cpp
