######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 1 09:35:42 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h manager.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp manager.cpp
