######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 14 21:41:04 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += preference.h
FORMS += preferenceGui.ui
SOURCES += main.cpp preference.cpp
